"""
SecureChat Authentication
=========================
Register, login, logout with bcrypt password hashing and Flask-Login sessions.
Rate-limited login attempts to prevent brute-force attacks.
"""

import re
import time
from datetime import datetime, timezone

import bcrypt
from flask import Blueprint, flash, jsonify, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from database import get_db
from models import User

auth_bp = Blueprint('auth', __name__, url_prefix='/auth')

# In-memory rate-limit store: { username: [attempt_count, lockout_until] }
_login_attempts = {}


def _is_rate_limited(username):
    """Check if the username is currently rate-limited."""
    from flask import current_app
    entry = _login_attempts.get(username)
    if not entry:
        return False
    count, lockout_until = entry
    if lockout_until and time.time() < lockout_until:
        return True
    if lockout_until and time.time() >= lockout_until:
        # Lockout expired — reset
        _login_attempts.pop(username, None)
        return False
    max_attempts = current_app.config.get('MAX_LOGIN_ATTEMPTS', 5)
    return count >= max_attempts


def _record_failed_attempt(username):
    """Increment failed login count; apply lockout if threshold reached."""
    from flask import current_app
    max_attempts = current_app.config.get('MAX_LOGIN_ATTEMPTS', 5)
    lockout_seconds = current_app.config.get('LOGIN_LOCKOUT_SECONDS', 300)

    entry = _login_attempts.get(username, [0, None])
    entry[0] += 1
    if entry[0] >= max_attempts:
        entry[1] = time.time() + lockout_seconds
    _login_attempts[username] = entry


def _clear_attempts(username):
    """Clear login attempt counter after successful login."""
    _login_attempts.pop(username, None)


def _validate_registration(data):
    """Validate registration input. Returns dict of errors or empty dict."""
    errors = {}

    username = (data.get('username') or '').strip()
    email = (data.get('email') or '').strip()
    password = data.get('password') or ''
    confirm = data.get('confirm_password') or ''
    public_key = data.get('public_key') or ''

    if not username or len(username) < 3:
        errors['username'] = 'Username must be at least 3 characters.'
    elif len(username) > 64:
        errors['username'] = 'Username must be at most 64 characters.'
    elif not re.match(r'^[a-zA-Z0-9_.\-]+$', username):
        errors['username'] = 'Invalid username characters.'

    if not email or '@' not in email:
        errors['email'] = 'Please enter a valid email address.'
    elif len(email) > 120:
        errors['email'] = 'Email is too long.'

    if not password or len(password) < 8:
        errors['password'] = 'Password must be at least 8 characters.'

    if password != confirm:
        errors['confirm_password'] = 'Passwords do not match.'

    if not public_key:
        errors['public_key'] = 'Public key is required (generated by the browser).'

    return errors


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    """Show registration page or register a new user."""
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))

    if request.method == 'GET':
        return render_template('register.html')

    data = request.get_json(silent=True) or {}

    # Validate
    errors = _validate_registration(data)
    if errors:
        return jsonify(success=False, errors=errors), 400

    username = data['username'].strip()
    email = data['email'].strip().lower()
    password = data['password']
    public_key = data['public_key']

    db = get_db()

    # Check uniqueness
    if db.query(User).filter_by(username=username).first():
        return jsonify(success=False, message='Username is already taken.'), 409
    if db.query(User).filter_by(email=email).first():
        return jsonify(success=False, message='Email is already registered.'), 409

    # Hash password
    password_hash = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

    # Create user
    user = User(
        username=username,
        email=email,
        password_hash=password_hash,
        public_key=public_key
    )
    db.add(user)
    db.commit()

    # Log in
    login_user(user)

    return jsonify(success=True, redirect=url_for('main.dashboard'))


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    """Show login page or authenticate user."""
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))

    if request.method == 'GET':
        return render_template('login.html')

    data = request.get_json(silent=True) or {}
    username = (data.get('username') or '').strip()
    password = data.get('password') or ''

    if not username or not password:
        return jsonify(success=False, message='Username and password are required.'), 400

    # Rate limit check
    if _is_rate_limited(username):
        return jsonify(success=False, message='Too many failed attempts. Please try again later.'), 429

    db = get_db()
    user = db.query(User).filter_by(username=username).first()

    if not user or not bcrypt.checkpw(password.encode('utf-8'), user.password_hash.encode('utf-8')):
        _record_failed_attempt(username)
        return jsonify(success=False, message='Invalid username or password.'), 401

    # Success
    _clear_attempts(username)
    user.last_seen = datetime.now(timezone.utc)
    db.commit()
    login_user(user)

    return jsonify(success=True, redirect=url_for('main.dashboard'))


@auth_bp.route('/logout', methods=['GET'])
@login_required
def logout():
    """Log out the current user."""
    db = get_db()
    current_user.last_seen = datetime.now(timezone.utc)
    db.commit()
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('auth.login'))
